### ISSUE TITLE
Link to qti not working

### ISSUE THREAD

**Issue by ShKlinkenberg** [ShareStats/ShareStats_website#3]
https://github.com/ShareStats/ShareStats_website/blob/24bd12deb0ecce6cecd936a6e9b321df05f84708/items-df.qmd#L14

Hi @tasospsy the link to the QTI download does not seem to be working. The URL of the other packages point to:

https://github.com/ShareStats/itembank/raw/packages/packages/zip/Assumptions/eur-assumptions-101-en.zip

But for the QTI one it seems to take a local path

file:///Users/sharonklinkenberg/GitHub/ShareStats_website/_site/,%20https://github.com/ShareStats/itembank/raw/packages/packages/qti/Assumptions/eur-assumptions-101-en-qti.zip

Ik can't find the exact issue for the variable going in to the functions seem to be the same. Could you have a look at this.

**Comment by tasospsy** [comment]
It was a typo, an extra ",". Now fixed.
